jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.1
      - run: dotnet build
      
#  test:
#  analyze:
#  package:
#  deploy:

name: cibuild

on:
  push:
    branches:
      - master






#person:
#  firstName: "jeremy" #string
#  lastName: 100 #number
#  middleName: true
#  alias:
#    - "dotnet"
#    - "lead"
#    - "subalias"